#!/bin/bash
cd "${0%/*}"
#load config

# check git

# check composer

# remove .git
rm -rf .git

# create bare repo for incoming
git init --bare deploy.git

# create post-received handler
mv post-receive/post-receive deploy.git/hooks/post-receive

# update permissions
chmod +x deploy.git/hooks/post-receive
chmod +x post-receive/master

chmod +x common/compose-tree

chmod +x zikula/deploy-tree
chmod +x zikula/fix_autoload

# create default working tree
mkdir workingtree

# create default deploy folder
mkdir deploy
