#!/bin/bash
#load config

# check git

# check composer

# remove .git
rm -rf .git

# create bare repo for incoming
git init --bare deploy.git

# create post-received handler
mv post-receive/post-receive deploy.git/hooks/post-receive

# update permissions
chmod +x deploy.git/hooks/post-receive
chmod +x post-receive/master

# create working tree
mkdir workingtree


