#!/bin/bash
#printenv
echo "   | Running branch handler $branch" | tee -a "$gitdeploy_log"

if [ ! -d "$gitdeploy_workingtree/$branch" ]
then
mkdir -p "$gitdeploy_workingtree/$branch"
echo "   | Working tree created: $gitdeploy_workingtree/$branch" | tee -a "$gitdeploy_log"
fi
echo "   | Working tree: $gitdeploy_workingtree/$branch" | tee -a "$gitdeploy_log"
rm -rf "$gitdeploy_workingtree/$branch"/*
echo "   | Working tree cleaned" | tee -a "$gitdeploy_log"

# recive push data
echo "   | Running git!" | tee -a "$gitdeploy_log"
GIT_WORK_TREE="$gitdeploy_workingtree/$branch" git checkout $branch -f &>> "$gitdeploy_logs/git-$branch-$NOW.log"
echo "   | Git done! - logfile: $gitdeploy_git_log" | tee -a "$gitdeploy_log"
# files are ready for deployment
echo "   | Working tree ready! in $gitdeploy_workingtree/$branch" | tee -a "$gitdeploy_log"

# dont do anything on master
# this is only a template file for your own branches
# start your own deployment procedure below

# end
echo "   | Branch handler $branch finished!" | tee -a "$gitdeploy_log"

