#!/bin/bash
cd ..
gitdeploy_root=$(pwd)
cd deploy.git

# Where to store the log information about the updates
LOGFILE="$gitdeploy_root/post-receive-$NOW.log"
echo "   | Running branch handler master" | tee -a "$LOGFILE"

# Where to store branch files
WORK_TREE="$gitdeploy_root/workingtree"
echo "   | Working tree: $WORK_TREE" | tee -a "$LOGFILE"

rm -rf "$WORK_TREE"/*
echo "   | Working tree cleaned" | tee -a "$LOGFILE"

GIT_WORK_TREE=$WORK_TREE git checkout master -f &>> "$LOGFILE"
echo "   | Working tree ready!" | tee -a "$LOGFILE"

#
# start your own deployment procedure for master here
#

#compose working dir using commons compose tree
echo "   | Running composer" | tee -a "$LOGFILE"
sh $gitdeploy_root/common/compose-tree "$WORK_TREE" &>> "$LOGFILE"

# clean dir before deploy
#rm -rf "$gitdeploy_root"/deploy/*
# deploy using zikula deploy script
sh $gitdeploy_root/zikula/deploy-tree "$WORK_TREE" "$gitdeploy_root/deploy"

#Zikula fix autoload
#sh $gitdeploy_root/zikula/fix_autoload "$gitdeploy_root/deploy"

# end
echo "   /===============================" | tee -a "$LOGFILE"

#git tag release_$NOW $target_branch
#echo "   | Tag name     : release_$NOW" | tee -a "$LOGFILE"
