#!/bin/bash
# timestamp
NOW=$(date +"%Y%m%d-%H%M")
cd ..
gitdeploy_root=$(pwd)
# Where to store the log information about the updates
LOGFILE="$gitdeploy_root/post-receive-$NOW.log"
touch $LOGFILE
cd deploy.git
echo "   /===============================" | tee -a "$LOGFILE"
echo "   | DEPLOYMENT"  | tee -a "$LOGFILE"
echo "   | Date     : $NOW" | tee -a "$LOGFILE"
echo "   | Received Push Request at $( date +%F )" | tee -a "$LOGFILE"
# read input
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
echo "   | Old SHA: $oldrev" | tee -a "$LOGFILE"
echo "   | New SHA: $newrev" | tee -a "$LOGFILE"
echo "   | Branch Name: $branch" | tee -a "$LOGFILE"

[ -f $gitdeploy_root/post-receive/$branch ] && sh $gitdeploy_root/post-receive/$branch || echo "   | Branch handler $branch not found at $gitdeploy_root/post-receive/$branch"

done
# end
echo "   /===============================" | tee -a "$LOGFILE"
