#!/bin/bash
#printenv
echo "   | Running branch handler $branch" | tee -a "$gitdeploy_log"

if [ ! -d "$gitdeploy_workingtree/$branch" ]; then
    mkdir -p "$gitdeploy_workingtree/$branch";
fi;
echo "   | Working tree: $gitdeploy_workingtree/$branch" | tee -a "$gitdeploy_log"
rm -rf "$gitdeploy_workingtree/$branch"/*
echo "   | Working tree cleaned" | tee -a "$gitdeploy_log"

# recive push data
echo "   | Running git!" | tee -a "$gitdeploy_log"
GIT_WORK_TREE="$gitdeploy_workingtree/$branch" git checkout $branch -f &>> "$gitdeploy_logs/git-$branch-$NOW.log"
echo "   | Git done! - logfile: $gitdeploy_git_log" | tee -a "$gitdeploy_log"

# 
echo "   | Working tree ready! in $gitdeploy_workingtree/$branch" | tee -a "$gitdeploy_log"

# Zikula specyfic deployment

# compose working dir using commons compose tree
# check if compooser.lock has changed ?
#
echo "   | Running common/compose-tree! - this will take a while" | tee -a "$gitdeploy_log"
sh $gitdeploy_home/common/compose-tree "$gitdeploy_workingtree/$branch" &>> "$gitdeploy_logs/composer-$branch-$NOW.log"
echo "   | Common/compose-tree done! - logfile: $gitdeploy_logs/composer-$branch-$NOW.log" | tee -a "$gitdeploy_log"

# deploy using zikula deploy script this will update deploy dir before deploying
sh $gitdeploy_home/zikula/deploy-upgrade "$gitdeploy_workingtree/$branch" "$gitdeploy_deploy" | tee -a "$gitdeploy_log"

#Zikula fix files
sh $gitdeploy_home/zikula/fix_autoload "$gitdeploy_deploy"

#Zikula upgrade
#sh $gitdeploy_home/zikula/upgrade "$gitdeploy_deploy" | tee -a "$gitdeploy_log"

# end
echo "   | Branch handler $branch finished!" | tee -a "$gitdeploy_log"

