#!/bin/bash
echo "   | Running common/compose-tree"
if [ -z "$1" ]; then echo "   | Error: No working tree specified"; exit 1; fi
WORK_TREE=$1
# Composer install
cd "$WORK_TREE" && composer install 
echo "   | Composer: packages installed"
